version: "2.4"
services:
  sh:
    build:
      context: .
      dockerfile: Dockerfile
    image: 127.0.0.1:5000/codekata/sh:unreleased
    volumes:
    - type: bind
      source: ./workspace
      target: /workspace
