version: "2.4"
services:
  ts:
    build:
      context: .
      dockerfile: Dockerfile
    image: 127.0.0.1:5000/codekata/ts:unreleased
#    env_file:
#      - .env
    environment:
      NODE_ENV: development
    volumes:
      - type: bind
        source: ./workspace
        target: /workspace
      - type: volume
        source: npm_cache
        target: /root/.npm
    ports:
      - 9229:9229

volumes:
  npm_cache:
    driver: local
    name: global_npm_cache
