version: "3.8"
services:
  go:
    image: golang:1.16
    user: "0" # root
    entrypoint: []
    command: ["bash"]
    healthcheck:
      disable: true
    ports:
    - mode: host
      target: 40000
      published: 40000
      protocol: tcp
    volumes:
    - type: volume
      source: go_cache
      target: /go/pkg/mod
    - type: bind
      source: ./workspace
      target: /workspace
    working_dir: /workspace
volumes:
  go_cache:
    driver: local
