version: "2.4"
services:
  ansible:
    build:
      context: .
      dockerfile: Dockerfile
    image: 127.0.0.1:5000/codekata/ansible:unreleased
#    env_file:
#      - .env
#    environment:
#      FOO: BAR
    volumes:
      - type: bind
        source: ./workspace
        target: /workspace
