version: "2.4"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: 127.0.0.1:5000/codekata/php:unreleased
#    env_file:
#      - .env
#    environment:
#      FOO: BAR
    volumes:
      - type: bind
        source: ./workspace
        target: /workspace
      - type: volume
        source: composer_cache
        target: /root/.composer/cache

volumes:
  composer_cache:
    driver: local
    name: global_composer_cache
